### ISSUE TITLE
Smart Contract : simplify withdrawal method for vault

### ISSUE THREAD

**Issue by computerpoet** [Cork-Technology/Depeg-swap#146]
# Overview
Right now the vault is in a state where it has an embedded router in it. I.e when user withdraw, all their assets(CT, DS) will be converted to RA by the vault. we want to simplify this by returning all their assets "as is" to minimize complexity. If the current functionality is desired, it should be made within a separate router

##  Task
- [x] new LV rates 
- [x] new market neutral withdrawal

**Comment by ziankork** [comment]
- [ ] new LV rates 
- [ ] new market neutral withdrawal

**Comment by ziankork** [comment]
The LV rates is still being worked on by Peter and his estimate that it'll finish tonight

**Comment by ziankork** [comment]
Still need more time on this as the math testing is taking more time from expected in #188

**Comment by ziankork** [comment]
still in discussion wither Peter and is waiting for a couple of confirmation regarding on how to define, determine and calculate the market value for each type of token(CT, DS, LP). After this it shouldn't be that hard to implement

**Comment by ziankork** [comment]
New spec document from peter(WIP) : https://www.notion.so/corkfi/Liquidity-Vault-LV-Deposit-Mechanism-LV-shares-calculation-138328fa34fd80da95b8e391c60d7d8a?pvs=4

need a little adjustments on the LP NAV calculation where RA is always constant at 1. Now it's determined by using CT/RA
