### ISSUE TITLE
Smart Contract: Implement Universal Asset Router for Auto-Token Conversion

### ISSUE THREAD

**Issue by yusak-cork** [Cork-Technology/Depeg-swap#162]
# Overview
Currently our protocol only supports depositing, swapping, and withdrawing only with the same tokens that’s in the market. This creates friction to use our protocols(especially around withdrawing) and there’s a need to build a router to handle input/output conversion. This design will be based around Pendle’s router implementation for the sake of not re-inventing the wheel.

## Tasks
- [ ] [Spec](https://www.notion.so/corkfi/Universal-Router-V1-1a4328fa34fd80b68e1bcf9d02d8d46b?pvs=4)(will be updated gradually as things get more clear in prototypes)
- [x] Deposit LV
- [x] Deposit PSM
- [x] Redeem LV
- [x] Repurchase
- [x] Redeem DS with DS & PA
- [x] Swap RA for DS
- [x] Swap DS for RA
- [x] Swap RA for CT
- [x] Swap CT for RA
