### ISSUE TITLE
Smart Contract : Liquidation update

### ISSUE THREAD

**Issue by ziankork** [Cork-Technology/Depeg-swap#223]
# Overview
Need to support partial fill in the liquidation contracts, see slack [thread](https://cork-protocol.slack.com/archives/C077Y0502JF/p1732529805174469)

## Tasks
- [x] [Specs](https://www.notion.so/corkfi/Universal-Liquidation-Mechanism-143328fa34fd8032a7a9ccdc31db98bc?pvs=4)
- [x] Child Contract Implementation
- [x] Main Liquidation Contract Adjustments
- [x] Vault Adjustments
- [x] Tests
