### ISSUE TITLE
Prepare for competition

### ISSUE THREAD

**Issue by siddhpurakaran** [Cork-Technology/Depeg-swap#224]
### Tasks
- [x] Test Deployment script with competition parameters 
- [x] Deploy Competition tokens
- [x] Deploy final version
- [x] Prepare final list of competition participants for funding
- [x] Send funds to participants
