### ISSUE TITLE
Smart Contract: Pause Vault for Liquidation

### ISSUE THREAD

**Issue by ziankork** [Cork-Technology/Depeg-swap#234]
See slack [thread](https://cork-protocol.slack.com/archives/C078JCU926T/p1732270300042789) for now

# Tasks
- [x] Enable withdrawing unliquidated PA's
- [x] Enable withdrawing idle RA's
- [x] Pause deposits when there's PA's on rollover (have to manually un pause)
- [ ] tests
