### ISSUE TITLE
Smart Contract: Vault Fee adjustment

### ISSUE THREAD

**Issue by ziankork** [Cork-Technology/Depeg-swap#247]
# Overview
Now all fees are accrued into the Vault. we need to take a % cut from every fees accrued at the time of generation, the % cut will be sent to the protocol treasury. 
For AMM, a % of the fees on every trade will be cut and sent directly to protocol treasury

## Task
- [x] Add method in the config contract to change vault treasury address
- [x] Stream LP fees to treasury in hook
- [x] cut a % of repurchase fee
- [x] cut a % of DS redemption fees
- [x] remove redeem early fees
- [x] [specs](https://www.notion.so/corkfi/Protocol-Fees-Distribution-173328fa34fd80339c4fe5219c19e181?pvs=4)
