### ISSUE TITLE
Linting issues

### ISSUE THREAD

**Issue by ziankork** [Cork-Technology/Depeg-swap#31]
# Overview
There are currently no automatic lint checking in workflow and no script to auto-lint tests and contracts

# Tasks
- [x] Add new workflow for lint-checking
- [x] Add script for linting tests
- [x] Add script for linting contracts
